services:
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./server/templates:/etc/nginx/templates
    environment:
      - NGINX_PORT=80
      - KAITEN_HOST=${KAITEN_HOST}
      - KAITEN_FILES=${KAITEN_FILES}