name: Publish

permissions:
  packages: write
  contents: write

on:
  workflow_run:
    workflows: ["CMake on multiple platforms"] 
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v4
      with:
        github-token: ${{ secrets.github_token }}
        path: ${{ github.workspace }}/artifacts
        run-id: ${{ github.event.workflow_run.id }}
    - run: ls -R ${{ github.workspace }}/artifacts

    - run: sudo apt -y install zip
    - run: zip -q -r binaries-windows.zip ${{ github.workspace }}/artifacts/windows-latest/Release
    - run: zip -q -r binaries-ubuntu.zip ${{ github.workspace }}/artifacts/ubuntu-latest

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: Latest build
        prerelease: true
        tag_name: 'master'
        files: |
          binaries-windows.zip
          binaries-ubuntu.zip
