name: Publish to github

permissions:
  packages: write
  contents: write

on:
  workflow_run:
    workflows: ["Build multiple platforms"]
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v4
      with:
        github-token: ${{ secrets.github_token }}
        path: ${{ github.workspace }}/artifacts
        run-id: ${{ github.event.workflow_run.id }}

    - run: sudo apt -y install zip
    - run: zip -jrq binaries-windows.zip ${{ github.workspace }}/artifacts/windows-latest/Release
    - run: zip -jrq binaries-ubuntu.zip ${{ github.workspace }}/artifacts/ubuntu-latest
    - run: zip -jrq binaries-android.zip ${{ github.workspace }}/artifacts/android-latest

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: Latest build
        prerelease: true
        tag_name: 'latest-build'
        files: |
          binaries-windows.zip
          binaries-ubuntu.zip
          binaries-android.zip
